# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:16
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('2858'), default_currency=b'USD', max_digits=4),
        ),
        migrations.AlterField(
            model_name='courses',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 9, 9, 42)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default='Your homie eats a cat with rabies to know more about archeology.  This cool guy my gardener met yesterday encourages a sloth for no apparent reason.  This cool guy my gardener met yesterday creates your homie to know more about archeology.  A sloth encourages a sloth to be able to make toast explode.  This cool guy my gardener met yesterday configures superman for a disease.  '),
        ),
    ]
