# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:16
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170505_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('6378'), default_currency=b'USD', max_digits=4),
        ),
        migrations.AlterField(
            model_name='courses',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 4, 17, 12)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default='A dude spies on a dude to be able to make toast explode.  My mom meets with my mom for no apparent reason.  The king encourages a dude to be able to make toast explode.  A dude creates a cat with rabies for a disease.  My mom treats my mom because the sky is green.  '),
        ),
    ]
