# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:14
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170505_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('6324'), default_currency=b'USD', max_digits=4),
        ),
        migrations.AlterField(
            model_name='courses',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 11, 1, 54)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default='This cool guy my gardener met yesterday flees from superman to make a pie.  A dude configures a cat with rabies to know more about archeology.  The king kicks my mom to be able to make toast explode.  My mom tries to automate a sloth for a disease.  A sloth spies on this cool guy my gardener met yesterday to make a pie.  '),
        ),
    ]
