# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:22
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170505_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('3357'), default_currency=b'USD', max_digits=4),
        ),
        migrations.AlterField(
            model_name='courses',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 16, 54, 59)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default='The king flees from my mom for a disease.  Superman kicks your homie to be able to make toast explode.  Superman kicks some guy to know more about archeology.  A dude configures a cat with rabies to make a pie.  The king kicks superman because the sky is green.  '),
        ),
    ]
