# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:53
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170505_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('7526'), default_currency=b'USD', max_digits=4),
        ),
        migrations.AlterField(
            model_name='courses',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 22, 5, 57)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default='A dude encourages superman to know more about archeology.  Your homie spies on the king to make a pie.  The king configures my mom for no apparent reason.  Your homie encourages this cool guy my gardener met yesterday to be able to make toast explode.  The king gives a cat with rabies to be able to make toast explode.  '),
        ),
    ]
